export const invoices = [
    {
        invoiceNumber: "FR0001",
        grossAmount: 150,
        currency: "$",
        status: "unpaid" as const,
        customerId: "é45645130",
        invoiceDescription: "Mission Molia",
        issuedDate: new Date(2023, 0, 12),
        paidDate: new Date(2025, 10, 3),
    },
    {
        invoiceNumber: "152465",
        grossAmount: 11250,
        currency: "€",
        status: "paid" as const,
        customerId: "é45645130",
        invoiceDescription: "ML Consulting",
        issuedDate: new Date(2023, 9, 3),
        paidDate: new Date(2025, 9, 3),
    },
    {
        invoiceNumber: "FR001",
        grossAmount: 11250,
        currency: "$",
        status: "unpaid" as const,
        customerId: "é45645130",
        invoiceDescription: "ML Consulting",
        issuedDate: new Date(2025, 4, 21),
        paidDate: new Date(2025, 9, 3),
    },
    {
        invoiceNumber: "EN0002",
        grossAmount: 9500,
        currency: "$",
        status: "paid" as const,
        customerId: "EHD",
        invoiceDescription: "ML Document AI expertise",
        issuedDate: new Date(2023, 2, 26),
    },
];
